[package]
name = "erock_edge"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "erock_edge"
path = "src/main.rs"

[dependencies]
erock = { path = "../" }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde_json = "1"
tracing = "0.1"
hyper = "0.14"
serde = { version = "1", features = ["derive"] }
cudarc = { version = "0.9", optional = true }
rhai = "1.18"
nom = "7.1"
