name: docs-ci
on: [pull_request, push]
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude-all-private '**/*.md'
